### ISSUE TITLE
Set default server to allow omitting server name from commands

### ISSUE THREAD

**Issue by psimyn** [makupi/pavlov-bot#56]
**Is your feature request related to a problem? Please describe.**

If the bot is being used for a single dedicated server, it's a bit annoying typing out the name every time. 

**Describe the solution you'd like**

Either:

1. if only 1 server is specified in servers.json, default to that
1. add a command to set a default server, and name defaults to that value if not provided

**Comment by frostyboskitzo** [comment]
Looking at the code for this (and I am no python guy, so cleverness might  be possible) it looks like all functions expect `server_name: str` as part of the function.

`bot/cogs/pavlov.py` contains the functions for things like switchmap; all functions contained therein refer to `server_name: str`.

It could be possible to execute a `while` or `for` against the imported servers json file, and if the count is 1, declare server_name as a default, but I'm not sure whether the structure of the functions needs to be rewritten if the function is only passed "some" of the arguments to infer a default. I know python supports this with fixed values, but unsure how this would parse to a server name....

For example:

`def exec_server_command(server_name: str = "default", server_cmd: str):` but I really am not sure if that'd fly. I dont have any dev/test environment set up for something like this. 

The other idea could be something like `def exec_server_command(server_cmd, *args)` and if there are no args, then assume the default server (we would need to declare a default server either earlier in the init when parsing the servers.json). If 1 arg is present , check it against server_names as normal. If more than 1 arg is present, drop the extra args (i.e. only use the first) and check that against the server name. This, I like better, because you could optionally use Args to parse commands to several servers at once:

```
~# ;switchmap UGC123123123 SND dedicated-private-server pavlov-aus-01 pavlov-aus-02
> Switching map to UGC123123123 on default-server 
> Switching map to UGC123123123 on pavlov-aus-01 
> Switching map to UGC123123123 on pavlov-aus-02
```

Some error handling would need to exist, but the existing error handling of "that server name doesn't exist, bro" is probably fine.

**Comment by frostyboskitzo** [comment]
Okay, so reading through the codebase, that's a pretty major refactor to define a default on init based on a flag in json `'default': 'true'` or something like that. there's 17 functions that use `server_name : str` and each function would need to have the parameters reordered (`*args` has to go at the end) as well as a new function to break down `*args` into none, one, or more than one `server_name`, _then_ parse that through the function in a while/for loop. Not a small amount of work, but it might be the smartest thing. I drafted up some code, but I didn't like it, so didn't commit it.

The other option which is "less work, less elegant" would be to refactor the order of function parameters so that `server_name :str` was the last parameter for each function, then rewrite it as `server_name :str = "default"` setting the parameter with a  default value. This _should_ mean that the functions which are executed with the 3 arguments, with the last argument being optional (`server_name`) and the rest of the function is more or less unchanged. the _downside_ to this is that users in the wild are used to the syntax of `;switchmap map_name game_mode server_name` will be fine, but those using `;command server_name command` will be thrown as their syntax would have to be `;command command server_name` (where server name is optional).

Some cleverness would still need to exist at the init to read server.json and declare if there's only 1 key, and theres' no servernotfound exception, then that server becomes the default. Or, the first server becomes the default no matter what. Or a default flag `'default': 'true'` is declared in the JSON. all are valid ideas.

@makupi this is your rodeo. What do you think?

**Comment by invicta-nz** [comment]
Seems like a lot of work to avoid 2 characters on the command string. That is, if you name your server "1" then you only have an additional ``" 1"`` to be added to each command to specify your single server.

**Comment by makupi** [comment]
The whole thing might even be a little bit easier than all that, but there are multiple ways to approach this:

### 1. "Default" server name
 - Since we have `server_name` as a last parameter for commands, this could rather easily be changed to an optional parameter, defaulting to e.g. `default`
- Now you can simply name your server in `servers.json` "default" and it would automatically be selected if no parameter is given.

### 2. Changing `Servers.get`
- Same as before, have `server_name` default to some value
- All `server_name` arguments run through `Servers.get` which looks through the configuration to find a matching server-name. This could be changed to recognize the "default" value and then either: If only one server exists, return this server. If multiple exist, check for some "default" flag, or "default" name. Or raise an Error.


Especially the first approach should be rather trivial. @invicta-nz what do you think?

**Comment by invicta-nz** [comment]
If the first one is a fairly simple change, then it would be easy to document how to make a single server the default

**Comment by psimyn** [comment]
thanks, "default" server name is an excellent idea! I'll have a shot at this in my fork.

I ultimately wanted to shorten switch map command to just `;switchmap <name>`. Server can use default and gamemode default can be inferred from the map. Probably not worth the saving of a few characters but I am very lazy when I have a headset on

**Comment by makupi** [comment]
> thanks, "default" server name is an excellent idea! I'll have a shot at this in my fork.

Awesome. Feel free to create a PR to this repository, otherwise I'll do it in the next couple days.

**Comment by frostyboskitzo** [comment]
> 
> 
> Seems like a lot of work to avoid 2 characters on the command string. That is, if you name your server "1" then you only have an additional `" 1"` to be added to each command to specify your single server.

... brb just renaming my server _really_ quick

**Comment by psimyn** [comment]
will PR something like this: https://gist.github.com/psimyn/6ccd22d38b55e4ee5898b68a2f636810
